---
- name: Apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
    - common
    - network

- name: Configure High Availability Routers
  hosts: routers
  become: yes
  roles:
    - router

- name: Configure Storage and Monitoring
  hosts: monitoring
  become: yes
  roles:
    - storage

- name: Configure Balancers
  hosts: balancers
  become: yes
  roles:
    - { role: balancer, tags: 'balanser' }

- name: Configure Frontends
  hosts: frontends
  become: yes
  roles:
    - frontend

- name: Configure Databases
  hosts: databases
  become: yes  # Установка требует прав рута. Указываю здесь, чтобы не писать в каждой задаче. Надо тестить.
  roles:
    - database
    
